/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.testmaximum.runner;

import java.util.Scanner;

public class TestMaximumMain {
	Integer a, b, c;

	public TestMaximumMain(Integer a, Integer b, Integer c) {
		this.a = a;
		this.b = b;
		this.c = c;
	}
	
	//Printing the largest number
	public void printMaxNumber() {
		System.out.println("The maximum number is : " + findMax(a, b, c));
	}
	
	//To find Maximum number from input
	public Integer findMax(Integer a, Integer b, Integer c) {
		Integer max = a;
		if (b.compareTo(max) > 0)
			max = b;
		if (c.compareTo(max) > 0)
			max = c;
		return max;
	}

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter three Integer numbers : ");
		Integer a = sc.nextInt();
		Integer b = sc.nextInt();
		Integer c = sc.nextInt();
		new TestMaximumMain(a, b, c).printMaxNumber();
		sc.close();
	}
}
