/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.testmaximum.runner;

import java.util.Arrays;

public class TestMaximumMain<E extends Comparable<E>> {
	E[] Values;

	// Constructor to initialize values
	public TestMaximumMain(E... Values) {
		this.Values = Values;
	}

	// Internal method to call findMaximum and printMaximum method
	public E testMaximum() {
		E max = findMaximum(this.Values);
		printMaximum(max);
		return max;
	}

	// Method to take optional arguments and find max
	public E findMaximum(E... Values) {
		E max;
		Arrays.sort(Values);
		max = Values[Values.length - 1];
		return max;
	}

	// Printing maximum value
	public void printMaximum(E max) {
		System.out.println("The maximum value is : " + max);
	}

	public static void main(String[] args) {
		new TestMaximumMain<Integer>(15, 4, 9, 78, 56, 48, 125, 98).testMaximum();
		new TestMaximumMain<Float>(15.6f, 4.2f, 9.5f, 78.1f, 56.9f, 48.3f, 100.5f, 98.9f).testMaximum();
		new TestMaximumMain<String>("PineApple", "Apple", "Grapes", "Mango").testMaximum();
	}
}
