/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.testmaximum.tester;

import org.junit.Test;

import com.blz.testmaximum.runner.TestMaximumMain;

import static org.junit.Assert.*;

import org.junit.Assert;

public class TestMaximumTest {
	@Test
	public void test_Given_MaxInteger_At1st_Position_Returns_Same_Number() {
		Integer actual=65;
		Integer expected=new TestMaximumMain(65, 45, 60).findMax(65, 45, 60);
		Assert.assertEquals(expected,actual);
	}
}

